language: python

python:
- 3.4
- 3.5
- 3.6

before_install:
#- sudo apt-get -qq update
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
- echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
- sudo apt-get -qq update
- sudo apt-get install -y mongodb-org

install:
- pip install pytest
- pip install .

script:
- py.test -v tests
