# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.11', '3.12', '3.13']
        mongodb-version: ['6.0', '7.0']
        pymongo-version: ['4.12.1', '4.6.1', '3.13.0']

        # More about the Python versions:
        #   3.13 - latest stable Python version
        #   3.11 - Python version in Debian 12
        #   3.9 - Python version in Debian 11

    steps:

    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install MongoDB
      run: |
        set -ex
        curl -fsSL https://pgp.mongodb.com/server-${{ matrix.mongodb-version }}.asc \
          | sudo gpg -o /usr/share/keyrings/mongodb-server.gpg --dearmor
        echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server.gpg ]" \
          "https://repo.mongodb.org/apt/ubuntu " \
          "`lsb_release --short --codename`/mongodb-org/${{ matrix.mongodb-version }} " \
          "multiverse" \
          | sudo tee /etc/apt/sources.list.d/mongodb-org.list
        sudo apt-get update
        sudo apt-get install -y mongodb-org-server
        dpkg -l | grep -i mongo
        dpkg -L mongodb-org-server

    - name: Install the package
      run: |
        python3 -m pip install pymongo==${{ matrix.pymongo-version }}
        python3 -m pip install .

    - name: Install pytest
      run: |
        python3 -m pip install pytest

    - name: Show package versions
      run: |
        python3 -m pip freeze

    - name: Test with pytest
      run: |
        python3 -m pytest -v --tb=native tests

    - name: Install flake8
      run: |
        python3 -m pip install flake8

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --statistics
